### ISSUE TITLE
rpm official repo

### ISSUE THREAD

**Issue by bitchecker** [Tox/toxic#306] opened 2015-03-02 10:47 UTC
why toxic is not present into rpm official repository?

**Comment by stqism** [comment] 2015-03-02 11:35
[This is actually incorrect.](https://repo.tox.im/x86_64/toxic-82.rpm)

**Comment by bitchecker** [comment] 2015-03-02 11:46
I think we should reopen because there are several issues unresolved dependencies:

Risoluzione dipendenze
--> Esecuzione del controllo di transazione
---> Pacchetto toxic.x86_64 0:0.5.2-318 settato per essere installato
--> Elaborazione dipendenza: libconfig9 per il pacchetto: toxic-0.5.2-318.x86_64
--> Elaborazione dipendenza: libncursesw5 per il pacchetto: toxic-0.5.2-318.x86_64
--> Elaborazione dipendenza: libnotify-bin per il pacchetto: toxic-0.5.2-318.x86_64
--> Elaborazione dipendenza: libalut0 per il pacchetto: toxic-0.5.2-318.x86_64
--> Risoluzione delle dipendenze completata
Errore: Pacchetto: toxic-0.5.2-318.x86_64 (tox)
            Richiede: libncursesw5
Errore: Pacchetto: toxic-0.5.2-318.x86_64 (tox)
            Richiede: libalut0
Errore: Pacchetto: toxic-0.5.2-318.x86_64 (tox)
            Richiede: libnotify-bin
Errore: Pacchetto: toxic-0.5.2-318.x86_64 (tox)
            Richiede: libconfig9

**Comment by stqism** [comment] 2015-03-02 12:25
Please translate the errors in to English next time.

Thankfully Italian isn't a very difficult language, but  to fix it I'd need to know what those packages are on Fedora. As I don't actually run Linux and Fedora doesn't provide a handy package contents search system like Debian and Ubuntu I have no way of finding out myself unless someone lets me know.

**Comment by bitchecker** [comment] 2015-03-02 12:59
@stqism sorry, i've pasted directly!

which information you need?

**Comment by stqism** [comment] 2015-03-03 00:28
@bitchecker The names of packages that contain those libraries. alut, ncurses, etc.

**Comment by bitchecker** [comment] 2015-03-03 08:12
@stqism https://github.com/irungentoo/toxcore/issues/1140#issue-47011803

**Comment by urras** [comment] 2015-03-03 14:59
Why is this a wontfix, @stqism?

@bitchecker I sincerely apologize, I thought this issue was fixed months ago. I'll try to get something working later on, but I'm a bit busy and won't be able to actively test and debug this issue until a bit later tonight.

**Comment by bitchecker** [comment] 2015-03-03 15:04
@urras ok :+1: 

please, if you can talk with someone that works on server repository, report also that is server that doesn't work properly too ( https://github.com/tux3/qTox/issues/1326#issue-59565991 ) is a big problem that can affect also toxic packages!!

**Comment by stqism** [comment] 2015-03-03 18:19
The issue is wontfix because I won't fix it until someone answers this: https://github.com/Tox/toxic/issues/306#issuecomment-76861687

**Comment by bitchecker** [comment] 2015-03-03 21:39
@stqism you're developer...you must to know wich libreries you need, i can only make a stupid search for try to help but i don't know which one of this results can works for you!

libconfig:
- libconfig-devel.i686 : Development files for libconfig
- libconfig-devel.x86_64 : Development files for libconfig
- libconfig.i686 : C/C++ configuration file library
- libconfig.x86_64 : C/C++ configuration file library

ncurses:
- ncurses.x86_64 : Ncurses support utilities
- ncurses-devel.i686 : Development files for the ncurses library
- ncurses-devel.x86_64 : Development files for the ncurses library
- ncurses-libs.i686 : Ncurses libraries
- ncurses-libs.x86_64 : Ncurses libraries
- ncurses-static.i686 : Static libraries for the ncurses library
- ncurses-static.x86_64 : Static libraries for the ncurses library

libnotify:
- libnotifymm.i686 : C++ interface for libnotify
- libnotify-devel.i686 : Development files for libnotify
- libnotify-devel.x86_64 : Development files for libnotify
- libnotifymm.x86_64 : C++ interface for libnotify
- libnotifymm-devel.i686 : Headers for developing programs that will use libnotifymm
- libnotifymm-devel.x86_64 : Headers for developing programs that will use libnotifymm
- libnotify.i686 : Desktop notification library
- libnotify.x86_64 : Desktop notification library

alut:
- freealut.i686 : Implementation of OpenAL's ALUT standard
- freealut.x86_64 : Implementation of OpenAL's ALUT standard
- freealut-devel.i686 : Development files for freealut
- freealut-devel.x86_64 : Development files for freealut

this is the output from my system when I try to look for the one that precedes the colon ( $ {name}: )
i hope that can be useful for you! :+1:

**Comment by stqism** [comment] 2015-03-03 21:43
@bitchecker Thanks for the start but I don't actually know Fedora and its packages.

**Comment by bitchecker** [comment] 2015-03-03 21:44
@stqism as I told you, for what I can count on me, I will try to help as much as possible, as also think I do! :+1:

**Comment by stqism** [comment] 2015-03-03 21:47
Again, those should be enough to make some guesses :)

**Comment by bitchecker** [comment] 2015-03-03 21:47
i hope! :D

**Comment by stqism** [comment] 2015-03-03 22:17
Fixed the deps off what you gave me, reopen if it doesn't launch.

**Closed by stqism** 2015-03-03 22:17 UTC
Labels: bug, wontfix
