### ISSUE TITLE
Sometimes, user handles can change color for seemingly no reason

### ISSUE THREAD

**Issue by HalosGhost** [Tox/toxic#343] opened 2015-06-22 01:53 UTC
While talking with one of my contacts, the following happened:

![screenshot](https://ptpb.pw/xWkY.png)

There is a small ``x`` after my post (which I did not type), and my contact's handle changed color (from the blue it normally was into the green mine normally is in the chat).

Any idea what could be causing this?

**Comment by JFreegman** [comment] 2015-06-24 20:07
Never seen that happen before. I'll look into it, and if you could give me steps to reproduce it that would be great.

**Comment by HalosGhost** [comment] 2015-06-24 20:48
Off the top of my head, I have no idea how to reproduce this. She and I were speaking regularly for a while and then this occurred and immediately after, it went back to normal.

I can tell you that I am using ``st`` with my own configuration, using [``tmux-256color-it``](http://aur.archlinux.org/packages/tmux-256color-it) for the terminfo, and I am using it within ``tmux``. I am also using ncurses-git with a custom ``wcwidth()`` and ``wcswidth()`` in a library loaded with ``LD_PRELOAD`` to allow for viewing high-plane unicode characters like “🐼”. I cannot, however, see how those would cause such a problem (particularly since it was just that one incident so far).

I suppose it might be due to our posting at exactly the same moment?

**Comment by JFreegman** [comment] 2015-06-24 22:00
>I suppose it might be due to our posting at exactly the same moment?

Yes it looks like some sort of race condition. I'm almost positive that it's a problem with the line printing logic.

**Comment by HalosGhost** [comment] 2015-06-24 22:13
Interesting. As you make progress on completion, I would appreciate it if you referenced commits which fix the issue; I'd love to read into the code to see what happened.

**Comment by JFreegman** [comment] 2015-07-01 02:49
Probably fixed with https://github.com/Tox/toxic/commit/84a027666838d226b80a2e7e944a74820f526523

If you experience this again please let me know and I'll reopen the issue.

**Closed by JFreegman** 2015-07-01 02:49 UTC

**Comment by HalosGhost** [comment] 2015-07-01 02:53
Great! I only experienced this that one time; so I doubt it is that common, but I will let you know! Thanks for the response!

**Comment by HalosGhost** [comment] 2015-07-28 22:11
@JFreegman, I just experienced this issue again.
